config/routes.rb
Rails.application.routes.draw do

  get 'projects/info' => 'projects#info', as: 'info'

  root 'projects#index'

  resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, presence: true
	validates :group, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
  end

  def create
    # @project = Project.create(params[:name])
    # @project = Project.create(params[:group])
    @project = Project.new
    @project.name = params[:name]
    @project.group = params[:group]
    @project.save

  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SEGP Industry Placement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <!--#######################################################-->
  <div class="wrapper banner">
    <div id="top_bar" class="flex_height">
      <div class="to_left">
        <!-- <a href="homepage.html"> -->
          <%= link_to(root_path) do %>
          <h1>University of Adelaide</h1>
          <p>School of Computer Science </p>
          
          <% end %>
        <!-- </a> -->
      </div>

      <div class="button to_right">
        <ul>
          <li><a href="login.html">Login</a></li>
          <li><a href="register.html">Register<a/></li>
        </ul>
      </div>
    </div>
  </div>
 <!--#######################################################-->
    <div class="wrapper navigation">
      <div id="navi" class="flex_height">
        <div class="to_left">
          <h1>SEGP Showcase</h1>
        </div>

        <div class="to_right">  
          <form action="#" method="post" id="search">  
            <input type="text" value="Search&hellip;" onfocus="this.value=(this.value=='Search&hellip;')? '' : this.value ;" />
            <input type="image" id="go" src="images/search_r.gif" alt="Search" />
          </form>
        </div>

        <div id="menu" class="button to_left">
          <ul>
            <li><%= link_to("Home", root_path ) %></li>
            <li><%= link_to("Projects", projects_path ) %></li>
            <li><%= link_to("Course Info", info_path ) %></li>
            <li><a href="contacts.html">Contacts</a></li>
          </ul>
        </div>
      </div>
    </div>
  <!--##############################################################-->
<!--   <div class="wrapper gallery">
    <div id="slides" class="shadow">
      <img src="images/example.gif" alt="" />
    </div>
  </div>
 -->
  <!--##############################################################-->
  <div class="wrapper content">
    <div id="news" class="flex_height shadow">
      <p class="justify">
        <%= yield %>
      </p>
    </div>
  </div>

  <!--##############################################################-->
  <div id="submit" class=button>
  <%= link_to("Submit Project", new_project_path) %>
  </div>

   <!--##############################################################-->
  <div class="wrapper footer">
    <div class="flex_height">
    </div>
  </div> 


</body>
</html>

app/views/projects/create.html.erb
<h1>Project created</h1>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h1>Home</h1>

<p>	
	<table>
			<tr>
		    <th>Project Name</th>
		    <th>Group Name</th>
		    <th></th>
		    <th></th>
		    <th></th>
		  </tr>
		<% @projects.each do |project| %>
		<tr>
			<td><%= project.name %></td>
			<td><%= project.group %></td>
		</tr>
		<% end %>
	</table>
</p>

app/views/projects/info.html.erb
<h1>Course Information</h1>
<p>Software Engineering Group Project is a course where we are assigned tasks to create a website</p>

app/views/projects/new.html.erb
<h1>Submit a new project</h1>
<p>
<%= form_tag(action: :create, method: "get") do %>
	Project name: <%= text_field_tag(:name)%>
	Group name: <%= text_field_tag(:group)%>
	<%= button_to "Create", action: :create %>
<% end %>
</p>

app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>